### ISSUE TITLE
有个问题请教下您

### ISSUE THREAD

**Issue by buaacarzp** [bubbliiiing/ssd-keras#9]
为什么训练的时候，读取的anchor坐标是pkl的，而预测的时候是从网络中去生成的,这个anchor的坐标不应该是单独作为一个变量吗？我看了下pkl中的anchor坐标跟下面这个坐标是一样的，为什么您要将anchor的坐标放入网络中尼？这也就是为什么网络的输出是33了，21个分类，4个gt与anchor的偏移量，4个var，4个anchor。
个人觉得这样的话会增加时间的开销，数组切片是O(n)的时间复杂度。
https://github.com/bubbliiiing/ssd-keras/blob/14c0aca3028ba3be267638a4c898075648cfbaeb/utils/utils.py#L203

**Comment by bubbliiiing** [comment]
emm，你的意思就是输出的时候也可以用pkl对吧。

**Comment by buaacarzp** [comment]
> emm，你的意思就是输出的时候也可以用pkl对吧。

**Comment by buaacarzp** [comment]
> emm，你的意思就是输出的时候也可以用pkl对吧。

是的，训练的时候用的是pkl中anchor的坐标，检测的时候用的是通过vgg网络的fp size 和stride 生成的锚框的坐标，个人感觉这是不是有点不协调，还是说哪里看错了。

**Comment by bubbliiiing** [comment]
学SSD的时候才刚开始搞目标检测，所以很多我现在觉得不合理的地方，但是和视频是配套的，所以不好改

**Comment by buaacarzp** [comment]
> 学SSD的时候才刚开始搞目标检测，所以很多我现在觉得不合理的地方，但是和视频是配套的，所以不好改

嗯  看出来了，不过up主还是很厉害的，比我强。 我看了这个函数的实现
